name: Smoke test

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  lint:
    if: ${{ github.repository == 'yannickcr/eslint-plugin-react' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - uses: ljharb/actions/node/install@main
      name: 'nvm install lts/* && npm install'
      with:
        node-version: 'lts/*'
        skip-ls-check: true
    - run: |
        npm link
        npm link eslint-plugin-react
    - uses: AriPerkkio/eslint-remote-tester-run-action@v1
      with:
        issue-title: "Results of weekly scheduled smoke test"
        eslint-remote-tester-config: test/eslint-remote-tester.config.js
